export const REGISTER_MODAL = 'MODAL/REGISTER_MODAL'
export const UNREGISTER_MODAL = 'MODAL/UNREGISTER_MODAL'
export const SHOW_MODAL_WINDOW = 'MODAL/SHOW_MODAL_WINDOW'
export const HIDE_MODAL_WINDOW = 'MODAL/HIDE_MODAL_WINDOW'
